<a href="https://colab.research.google.com/github/hafizzx/python-projects/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
df = pd.read_csv("/content/students_150_multiple_features.csv")

df.head()

,CGPA,IQ_Level,Field_Interest,Programming_Skill,Communication_Skill,Salary_Package_PKR
0,2.75,117.0,1.0,2.0,9.0,319694.0
1,3.90,85.0,5.0,3.0,2.0,344377.0
2,3.46,103.0,6.0,1.0,9.0,335458.0
3,3.20,86.0,3.0,1.0,1.0,266603.0
4,2.31,137.0,9.0,3.0,1.0,317019.0

In [4]:
df.shape

(150, 6)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CGPA                 149 non-null    float64
 1   IQ_Level             149 non-null    float64
 2   Field_Interest       149 non-null    float64
 3   Programming_Skill    149 non-null    float64
 4   Communication_Skill  149 non-null    float64
 5   Salary_Package_PKR   149 non-null    float64
dtypes: float64(6)
memory usage: 7.2 KB

In [6]:
df.describe()

,CGPA,IQ_Level,Field_Interest,Programming_Skill,Communication_Skill,Salary_Package_PKR
count,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000
mean,2.940403,112.302013,5.724832,5.510067,5.161074,376430.530201
std,0.591672,16.219651,2.983873,2.990113,2.924886,69424.453617
min,2.010000,85.000000,1.000000,1.000000,1.000000,184787.000000
25%,2.420000,100.000000,3.000000,3.000000,2.000000,329775.000000
50%,2.880000,113.000000,6.000000,5.000000,5.000000,374691.000000
75%,3.460000,124.000000,8.000000,8.000000,8.000000,430449.000000
max,3.970000,140.000000,10.000000,10.000000,10.000000,500000.000000

In [7]:
df.isnull().sum()

CGPA                   1
IQ_Level               1
Field_Interest         1
Programming_Skill      1
Communication_Skill    1
Salary_Package_PKR     1
dtype: int64

In [8]:
df = df.fillna(df.mean(numeric_only=True))

In [9]:
df.isnull().sum()

CGPA                   0
IQ_Level               0
Field_Interest         0
Programming_Skill      0
Communication_Skill    0
Salary_Package_PKR     0
dtype: int64

In [10]:
fig = px.scatter(
    df,
    x="CGPA",
    y="Salary_Package_PKR",
    title="CGPA vs Salary",
    trendline="ols"
)

fig.show()

In [11]:
fig = px.scatter(
    df,
    x="IQ_Level",
    y="Salary_Package_PKR",
    title="IQ Level vs Salary",
    trendline="ols"
)

fig.show()

In [12]:
fig = px.scatter(
    df,
    x="Communication_Skill",
    y="Salary_Package_PKR",
    title="Communication Skill vs Salary",
    trendline="ols"
)

fig.show()

In [13]:
features = [
    "CGPA",
    "IQ_Level",
    "Field_Interest",
    "Programming_Skill",
    "Communication_Skill"
]

X = df[features].values

y = df["Salary_Package_PKR"].values

In [14]:
X

array([[  2.75      , 117.        ,   1.        ,   2.        ,
          9.        ],
       [  3.9       ,  85.        ,   5.        ,   3.        ,
          2.        ],
       [  3.46      , 103.        ,   6.        ,   1.        ,
          9.        ],
       [  3.2       ,  86.        ,   3.        ,   1.        ,
          1.        ],
       [  2.31      , 137.        ,   9.        ,   3.        ,
          1.        ],
       [  2.31      , 128.        ,   5.        ,   5.        ,
          5.        ],
       [  2.12      , 110.        ,   8.        ,   3.        ,
          6.        ],
       [  2.94040268, 116.        ,   1.        ,   1.        ,
          6.        ],
       [  3.2       ,  90.        ,   5.        ,   1.        ,
          3.        ],
       [  3.42      , 116.        ,   3.        ,   8.        ,
          7.        ],
       [  2.04      , 139.        ,   1.        ,  10.        ,
          9.        ],
       [  3.94      ,  88.        ,   4.        ,   2.        ,
         10.        ],
       [  3.66      , 139.        ,   5.        ,   3.        ,
          8.        ],
       [  2.42      ,  95.        ,   7.        ,   2.        ,
          6.        ],
       [  2.36      , 140.        ,   1.        ,   3.        ,
          8.        ],
       [  2.37      , 101.        ,   3.        ,   7.        ,
          5.        ],
       [  2.61      , 122.        ,   2.        ,   1.        ,
          8.        ],
       [  3.05      , 108.        ,   9.        ,  10.        ,
         10.        ],
       [  2.86      ,  89.        ,  10.        ,   8.        ,
          4.        ],
       [  2.58      , 136.        ,   6.        ,  10.        ,
         10.        ],
       [  3.22      , 118.        ,  10.        ,  10.        ,
          8.        ],
       [  2.28      ,  90.        ,   3.        ,  10.        ,
         10.        ],
       [  2.58      , 106.        ,   8.        ,   2.        ,
          2.        ],
       [  2.73      ,  95.        ,   8.        ,   3.        ,
          5.        ],
       [  2.91      , 112.30201342,   2.        ,   9.        ,
          9.        ],
       [  3.57      , 100.        ,   6.        ,   7.        ,
          4.        ],
       [  2.4       , 117.        ,   7.        ,   4.        ,
          6.        ],
       [  3.03      ,  93.        ,   2.        ,  10.        ,
          1.        ],
       [  3.18      ,  90.        ,  10.        ,   5.        ,
          9.        ],
       [  2.09      , 100.        ,   2.        ,   2.        ,
          1.        ],
       [  3.22      , 113.        ,  10.        ,   8.        ,
          5.        ],
       [  2.34      ,  87.        ,   1.        ,   4.        ,
          4.        ],
       [  2.13      , 104.        ,   8.        ,   9.        ,
          3.        ],
       [  3.9       , 120.        ,   1.        ,   5.        ,
          6.        ],
       [  3.93      , 103.        ,   9.        ,   9.        ,
          2.        ],
       [  3.62      , 110.        ,   6.        ,   4.        ,
          3.        ],
       [  2.61      ,  87.        ,   7.        ,  10.        ,
          5.        ],
       [  2.2       , 103.        ,  10.        ,   5.        ,
          9.        ],
       [  3.37      , 104.        ,   7.        ,   9.        ,
          2.        ],
       [  2.88      , 116.        ,  10.        ,   8.        ,
         10.        ],
       [  2.24      ,  91.        ,   3.        ,   3.        ,
          8.        ],
       [  2.99      , 136.        ,   2.        ,   1.        ,
          2.        ],
       [  2.07      , 125.        ,   9.        ,   3.        ,
          5.        ],
       [  3.82      , 117.        ,   8.        ,   4.        ,
          7.        ],
       [  2.52      , 124.        ,  10.        ,   2.        ,
          8.        ],
       [  3.33      , 123.        ,   7.        ,   1.        ,
          1.        ],
       [  2.62      , 102.        ,   9.        ,   7.        ,
          6.        ],
       [  3.04      , 124.        ,   4.        ,   8.        ,
          1.        ],
       [  3.09      ,  85.        ,   4.        ,   7.        ,
          2.        ],
       [  2.37      ,  95.        ,   1.        ,   5.        ,
          1.        ],
       [  3.94      , 112.        ,   8.        ,   1.        ,
          5.        ],
       [  3.55      , 109.        ,   5.72483221,   7.        ,
         10.        ],
       [  3.88      , 134.        ,   7.        ,   7.        ,
          9.        ],
       [  3.79      , 107.        ,   2.        ,   9.        ,
          6.        ],
       [  3.2       , 115.        ,   2.        ,   3.        ,
          1.        ],
       [  3.84      , 114.        ,   7.        ,   9.        ,
          1.        ],
       [  2.18      , 126.        ,   6.        ,   1.        ,
          2.        ],
       [  2.39      , 119.        ,   3.        ,   1.        ,
          9.        ],
       [  2.09      ,  91.        ,   9.        ,   4.        ,
          3.        ],
       [  2.65      , 100.        ,  10.        ,   9.        ,
          1.        ],
       [  2.78      , 110.        ,   6.        ,   6.        ,
          5.        ],
       [  2.54      , 132.        ,  10.        ,   3.        ,
          7.        ],
       [  3.66      , 136.        ,  10.        ,   1.        ,
          6.        ],
       [  2.71      , 133.        ,   6.        ,   4.        ,
          1.        ],
       [  2.56      ,  86.        ,   1.        ,   9.        ,
          5.        ],
       [  3.09      ,  85.        ,   4.        ,   3.        ,
          5.        ],
       [  2.28      , 132.        ,  10.        ,   9.        ,
          6.        ],
       [  3.6       ,  96.        ,   6.        ,   7.        ,
          3.        ],
       [  2.15      ,  89.        ,   6.        ,   4.        ,
          5.        ],
       [  3.97      , 121.        ,   5.        ,   3.        ,
          7.        ],
       [  3.54      , 116.        ,   1.        ,  10.        ,
          5.        ],
       [  2.4       , 139.        ,   8.        ,   5.        ,
          5.        ],
       [  2.01      ,  93.        ,   5.        ,   5.        ,
          5.        ],
       [  3.63      , 125.        ,   5.        ,   3.        ,
         10.        ],
       [  3.41      , 119.        ,   7.        ,   9.        ,
         10.        ],
       [  3.46      , 103.        ,   4.        ,   4.        ,
          3.        ],
       [  3.54      , 132.        ,   6.        ,   5.        ,
          1.        ],
       [  2.15      , 100.        ,   4.        ,   4.        ,
          5.        ],
       [  2.72      ,  87.        ,   3.        ,   5.51006711,
          9.        ],
       [  2.23      , 104.        ,   7.        ,   7.        ,
          1.        ],
       [  3.73      , 108.        ,   8.        ,   9.        ,
          3.        ],
       [  3.25      , 138.        ,   4.        ,   7.        ,
          4.        ],
       [  2.66      , 140.        ,   2.        ,   5.        ,
          1.        ],
       [  2.13      , 117.        ,  10.        ,  10.        ,
          1.        ],
       [  2.62      , 108.        ,   3.        ,  10.        ,
          8.        ],
       [  2.65      , 136.        ,   1.        ,   7.        ,
          2.        ],
       [  3.46      ,  95.        ,   8.        ,  10.        ,
          8.        ],
       [  3.28      , 133.        ,   3.        ,   5.        ,
          7.        ],
       [  3.77      ,  92.        ,  10.        ,   3.        ,
         10.        ],
       [  2.94      , 120.        ,   7.        ,   7.        ,
         10.        ],
       [  2.24      , 122.        ,  10.        ,   2.        ,
          2.        ],
       [  3.43      , 124.        ,   5.        ,   9.        ,
          6.        ],
       [  3.52      , 104.        ,  10.        ,  10.        ,
          6.        ],
       [  3.12      , 119.        ,   5.        ,  10.        ,
          3.        ],
       [  3.54      , 132.        ,   7.        ,   1.        ,
          2.        ],
       [  2.99      , 109.        ,   9.        ,   6.        ,
          1.        ],
       [  3.05      , 119.        ,   5.        ,   7.        ,
          6.        ],
       [  2.86      , 109.        ,   1.        ,   8.        ,
          5.        ],
       [  2.05      , 113.        ,  10.        ,  10.        ,
          9.        ],
       [  2.22      , 102.        ,  10.        ,   9.        ,
          1.        ],
       [  2.06      , 130.        ,   1.        ,   2.        ,
          7.        ],
       [  3.27      , 102.        ,   2.        ,  10.        ,
          5.        ],
       [  2.63      ,  86.        ,   6.        ,   2.        ,
          5.        ],
       [  3.02      , 138.        ,   9.        ,   5.        ,
          5.16107383],
       [  3.82      , 119.        ,   8.        ,   5.        ,
          3.        ],
       [  2.5       , 100.        ,   5.        ,   6.        ,
          7.        ],
       [  2.82      , 125.        ,   1.        ,   3.        ,
          6.        ],
       [  3.51      , 120.        ,   7.        ,   8.        ,
          2.        ],
       [  2.46      , 117.        ,   5.        ,   1.        ,
          6.        ],
       [  2.15      ,  88.        ,   6.        ,   6.        ,
          2.        ],
       [  2.58      , 117.        ,   7.        ,   4.        ,
          2.        ],
       [  2.32      ,  98.        ,   3.        ,   1.        ,
          2.        ],
       [  3.86      , 105.        ,  10.        ,   7.        ,
          3.        ],
       [  3.62      , 132.        ,   3.        ,   9.        ,
          2.        ],
       [  3.27      , 104.        ,   5.        ,   4.        ,
          4.        ],
       [  3.74      , 140.        ,   6.        ,   4.        ,
          9.        ],
       [  3.61      ,  92.        ,   9.        ,   6.        ,
          6.        ],
       [  2.37      ,  91.        ,   5.        ,   3.        ,
          1.        ],
       [  3.79      ,  87.        ,   1.        ,   6.        ,
          8.        ],
       [  3.08      , 101.        ,   4.        ,   7.        ,
          7.        ],
       [  3.61      , 117.        ,   5.        ,  10.        ,
         10.        ],
       [  3.79      , 132.        ,  10.        ,  10.        ,
          3.        ],
       [  2.64      ,  96.        ,  10.        ,   3.        ,
          1.        ],
       [  2.22      , 135.        ,   5.        ,   7.        ,
          5.        ],
       [  2.46      , 106.        ,   7.        ,   3.        ,
          4.        ],
       [  2.85      , 139.        ,   4.        ,   2.        ,
         10.        ],
       [  3.64      , 106.        ,   1.        ,  10.        ,
          8.        ],
       [  3.72      , 130.        ,   5.        ,   4.        ,
          1.        ],
       [  2.01      , 114.        ,   7.        ,   8.        ,
         10.        ],
       [  3.02      , 122.        ,  10.        ,   9.        ,
          1.        ],
       [  2.83      , 122.        ,  10.        ,   7.        ,
          4.        ],
       [  2.44      , 129.        ,   6.        ,   1.        ,
          8.        ],
       [  2.24      , 135.        ,   5.        ,   3.        ,
          5.        ],
       [  2.68      , 138.        ,   4.        ,   9.        ,
          2.        ],
       [  3.89      ,  92.        ,   2.        ,   1.        ,
          6.        ],
       [  2.65      , 111.        ,   4.        ,   9.        ,
          5.        ],
       [  3.04      , 111.        ,  10.        ,   8.        ,
          2.        ],
       [  3.41      , 118.        ,  10.        ,   1.        ,
          3.        ],
       [  2.73      , 105.        ,   3.        ,   6.        ,
          9.        ],
       [  3.94      , 114.        ,  10.        ,   5.        ,
          7.        ],
       [  3.92      , 117.        ,   1.        ,   6.        ,
          7.        ],
       [  2.5       , 112.        ,   8.        ,  10.        ,
          6.        ],
       [  2.99      , 131.        ,   5.        ,   5.        ,
          8.        ],
       [  2.6       , 117.        ,   4.        ,   6.        ,
          4.        ],
       [  2.57      ,  89.        ,   8.        ,   5.        ,
          8.        ],
       [  2.07      , 132.        ,   7.        ,   5.        ,
          4.        ],
       [  3.22      , 103.        ,   2.        ,   4.        ,
          8.        ],
       [  3.01      ,  88.        ,   1.        ,   3.        ,
          9.        ],
       [  2.1       , 119.        ,   4.        ,   3.        ,
          3.        ],
       [  2.56      , 133.        ,   8.        ,   4.        ,
          3.        ]])

In [15]:
y

array([319694.        , 344377.        , 335458.        , 266603.        ,
       317019.        , 362733.        , 311304.        , 330881.        ,
       332073.        , 482741.        , 403051.        , 377221.        ,
       416233.        , 278733.        , 296969.        , 312360.        ,
       343706.        , 487069.        , 373949.        , 465842.        ,
       500000.        , 374691.        , 320792.        , 333525.        ,
       444818.        , 390691.        , 388518.        , 356112.        ,
       433805.        , 184787.        , 468996.        , 258677.        ,
       333556.        , 353523.        , 479142.        , 367981.        ,
       398098.        , 345724.        , 382187.        , 479967.        ,
       265655.        , 236633.        , 364777.        , 412509.        ,
       439533.        , 319200.        , 406239.        , 416574.        ,
       371386.        , 292853.        , 359323.        , 404603.        ,
       500000.        , 453394.        , 297719.        , 411450.        ,
       279214.        , 289544.        , 291244.        , 337051.        ,
       387737.        , 393030.        , 474479.        , 332737.        ,
       335759.        , 328195.        , 395146.        , 466417.        ,
       274230.        , 431564.        , 438415.        , 359630.        ,
       329775.        , 430449.        , 489263.        , 349063.        ,
       414506.        , 278270.        , 352248.        , 279678.        ,
       444101.        , 357530.        , 364525.        , 441400.        ,
       413865.        , 306685.        , 500000.        , 380690.        ,
       438870.        , 447388.        , 325688.        , 470895.        ,
       500000.        , 418587.        , 380103.        , 373670.        ,
       417483.        , 363032.        , 458071.        , 386149.        ,
       254539.        , 412668.        , 303135.        , 371922.        ,
       424349.        , 361203.        , 353932.        , 454223.        ,
       337909.        , 277041.        , 333055.        , 240343.        ,
       403441.        , 465970.        , 304677.        , 484324.        ,
       450771.        , 192710.        , 324173.        , 420612.        ,
       500000.        , 498378.        , 295353.        , 375015.        ,
       310281.        , 396360.        , 451390.        , 422776.        ,
       417852.        , 456219.        , 414997.        , 316767.        ,
       376430.53020134, 432824.        , 317243.        , 385513.        ,
       367280.        , 392495.        , 417230.        , 456059.        ,
       491561.        , 430556.        , 337077.        , 329362.        ,
       394461.        , 387183.        , 366152.        , 345790.        ,
       238555.        , 340593.        ])

In [16]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (150, 5)
y shape: (150,)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [20]:
print("Training:", X_train.shape)
print("Testing:", X_test.shape)

Training: (120, 5)
Testing: (30, 5)

In [21]:
model = LinearRegression()

In [22]:
model.fit(X_train, y_train)

LinearRegression()

In [25]:
y_test

array([430449.        , 373949.        , 324173.        , 352248.        ,
       414506.        , 258677.        , 335759.        , 430556.        ,
       274230.        , 364525.        , 333055.        , 416233.        ,
       398098.        , 482741.        , 465842.        , 279214.        ,
       424349.        , 431564.        , 411450.        , 376430.53020134,
       184787.        , 422776.        , 388518.        , 417852.        ,
       316767.        , 387183.        , 337909.        , 329362.        ,
       319200.        , 468996.        ])

In [29]:
y_pred = model.predict(X_test)

In [30]:
y_pred

array([426853.06500439, 401445.38954033, 397729.89552887, 353098.5719638 ,
       388246.48880873, 260331.72000014, 341023.10781643, 427245.31576836,
       293197.53642674, 318375.82803668, 324115.16112147, 424593.55331513,
       397721.36584467, 431618.92093198, 469792.9279927 , 265641.49065706,
       422349.6582033 , 418988.56578481, 445794.06724375, 317903.34323045,
       215916.1789671 , 377609.52767584, 345460.60851411, 401542.86683886,
       329944.44916371, 336091.65943403, 298444.43575474, 345098.23695594,
       326624.81355687, 449721.07279389])

In [31]:
mse = mean_squared_error(y_test, y_pred)

print("MSE:", mse)

MSE: 909193631.7624493

In [32]:
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error

model = SGDRegressor(
    max_iter=1000,
    learning_rate="constant",
    eta0=0.01,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Weights:", model.coef_)
print("Bias:", model.intercept_)

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

Weights: [ 1.68549760e+11  9.32632567e+10  7.51168490e+11 -1.60273642e+11
 -6.58744276e+10]
Bias: [2.2585523e+10]
MSE: 2.0609580124431882e+26